sensu/sensu-go-ansible

plugins/module_utils/arguments.py, plugins/module_utils/client.py, plugins/module_utils/errors.py, plugins/module_utils/response.py, plugins/module_utils/utils.py, plugins/modules/sensu_go_asset.py, plugins/modules/sensu_go_asset_info.py, tests/unit/module_utils/test_arguments.py, tests/unit/module_utils/test_client.py, tests/unit/module_utils/test_response.py, tests/unit/module_utils/test_utils.py, tests/unit/modules/common/sensu_go_object.py, tests/unit/modules/common/sensu_go_object_info.py, tests/unit/modules/common/utils.py, tests/unit/modules/test_sensu_go_asset.py, tests/unit/modules/test_sensu_go_asset_info.py
Original code that we inherited is only modular on the surface. Its various components share so much state between them that it is almost impossible to validate the correctness of each element separately.
Changes in this pull request split the functionality into three separate layers:
1. the HTTP layer that we can use to interact with the Sensu's web API (`Response` and `Client` classes),
2. the utility layer that contains various utility functions that help us synchronize the playbook and Sensu server states (`utils` module), and
3. modules that are responsible for splitting transforming the task parameters into payload for the synchronization functions.
This separation of concerns allows us to write robust tests for each component without risking an exponential explosion of test …
=> Cleanly separate module utils from Ansible internals

plugins/module_utils/client.py, plugins/module_utils/debug.py
With this commit we introduce a bit hackish yet useful debug logging for modules. Logging is disabled by default, you need to specify env variable in the playbook to turn it on:
```
environment:
SENSU_ANSIBLE_DEBUG: yes
```
Then the log file `/tmp/sensu-ansible.log` will appear on target host. For now we only log all the API requests (with payloads) because that's what we usually need to see.
=> Introduce simple debug logging

galaxy.yml
The version bump is a bit larger than one would expect because we broke the end-user API.
=> Bump version to 0.7.0

tests/integration/modules/molecule/asset/playbook.yml, tests/integration/modules/molecule/check/playbook.yml, tests/integration/modules/molecule/pipe_handler/playbook.yml, tests/integration/modules/molecule/sensu_go_filter/playbook.yml, tests/integration/modules/molecule/sensu_go_mutator/playbook.yml
It's time to start resolving the issues :) 
This one sets the `gather_facts` of module integration tests to `false`.
Closes: #37
=> Set `gather_facts: no` for module integration tests

.circleci/config.yml, roles/install/README.md, roles/install/defaults/main.yml, roles/install/tasks/apt/install.yml, roles/install/tasks/apt/install_one.yml, roles/install/tasks/apt/prepare.yml, roles/install/tasks/main.yml, roles/install/tasks/yum/install.yml, roles/install/tasks/yum/install_one.yml, roles/install/tasks/yum/prepare.yml, roles/install/vars/CentOS.yml, roles/install/vars/Ubuntu.yml, tests/integration/roles/install/molecule/centos/Dockerfile.j2, tests/integration/roles/install/molecule/centos/molecule.yml, tests/integration/roles/install/molecule/centos/playbook.yml, tests/integration/roles/install/molecule/centos/tests/test_centos.py, tests/integration/roles/install/molecule/shared/Dockerfile.j2, tests/integration/roles/install/molecule/shared/base.yml, tests/integration/roles/install/molecule/shared/playbook.yml, tests/integration/roles/install/molecule/shared/tests/test_latest_installed.py, tests/integration/roles/install/molecule/shared/tests/test_older_installed.py, tests/integration/roles/install/molecule/ubuntu/Dockerfile.j2, tests/integration/roles/install/molecule/ubuntu/molecule.yml, tests/integration/roles/install/molecule/ubuntu/playbook.yml, tests/integration/roles/install/molecule/ubuntu/tests/test_ubuntu.py
With this commit we introduce a role that configures target's package manager and then installs desired Sensu Go binary with it. Following binaries are currently present:
- sensu-go-backend
- sensu-go-agent
- sensu-go-cli
Currently the role supports following target platforms:
- Centos 6 & 7
- Ubuntu 14.04 & 16.04 & 18.04 & 18.10 & 19.04
Role allows you to either install latest version of the component or specify specific version, but that version must exist in the stable package repository.
=> The sensu.sensu_go.install role

plugins/modules/socket_handler.py, tests/integration/modules/molecule/socket_handler/Dockerfile.j2, tests/integration/modules/molecule/socket_handler/molecule.yml, tests/integration/modules/molecule/socket_handler/playbook.yml, tests/unit/modules/test_socket_handler.py
With this commit we introduce module that manages TCP/UDP sensu handler. PR is dependent on https://github.com/sensu/sensu-go-ansible/pull/35 which includes `handler_info` module, that is required for integration tests of this module.
Addressing issue: https://github.com/sensu/sensu-go-ansible/issues/20
=> Add socket handler module

.circleci/config.yml
The first commit in this PR fixes a typo that caused the daily test against a released version of collection to fail. The second commit adds additional checks on the `stable` branch. Running them as soon as we release a new stable version should allow us to catch any bugs faster.
=> Stable test fixes

.circleci/config.yml
This is hopefully one of the last pre-release version bumps before we can switch our tests to the stable Ansible version.
=> Bump Ansible version to 2.9.0rc1

plugins/modules/asset.py
There was still old `download_url` in the example.
=> Fix asset example

roles/backend/README.md, roles/backend/defaults/main.yml, roles/backend/templates/backend.yml.j2, tests/integration/roles/backend/molecule/config/Dockerfile.j2, tests/integration/roles/backend/molecule/config/molecule.yml, tests/integration/roles/backend/molecule/config/playbook.yml
This expands the list of supported variables in the role, which translate into the Sensu backend's configuration file.
This commit addresses the configurations of Sensu backend and Sensu agent, the API and dashboard. I skipped the settings that I consider managed and the subject of future commits: caching, KPI-related settings, and etcd store settings.
References:
* https://docs.sensu.io/sensu-go/5.14/reference/backend/#configuration
* https://docs.sensu.io/sensu-go/5.14/files/backend.yml
=> Add initial support for backend config

plugins/modules/asset.py
Cleaned up some required values that are only required when creating asset and some default values that are not actually defaults. I'm wondering why ansible sanity tester didn't complain.
=> Clean up asset's documentation

.circleci/config.yml
Previous versions of Ansible have troubles installing collections from the Ansible galaxy.
=> Bump Ansible version to 2.9.0rc4

.gitignore, roles/agent/meta/main.yml, roles/backend/meta/main.yml, roles/install/meta/main.yml
Up until now, we had no metadata attached to the individual roles and galaxy.ansible.com was completely fine with this. But today, things started failing when we tried to publish a new release of our collection. ansible-galaxy command reported back this:
Galaxy import process failed: Role metadata not found (Code: GLW0002)
A quick search through the galaxy sources revealed that this error is raised if no metadata file can be found in the role directory. And here we are, adding a fresh set of metadata to our roles.
Does this fix our publish problem? Heck if I know ;) I think it might, but cannot be sure.
=> Add metadata to roles

.circleci/config.yml
Up until now we ran all of our jobs in parallel. And while this sounds great in theory, it wastes quite a few resources when one of the short-running tests fail.
This is why we split the CI jobs into two categories: fast and slow ones. Now we first run the fast ones and then proceed to run slow ones. Note that the slow jobs are only run if all of the fast ones finished successfully.
This saves a ton if resources if one of the fast tests fails.
/cc @mancabizjak
=> Split CI pipeline into stages

roles/backend/README.md, roles/backend/templates/backend.yml.j2, tests/integration/roles/backend/molecule/config/playbook.yml
We now allow for a user change of the configurations that were previously baked into the template: `state-dir`.
=> Address special case backend configs

HACKING.rst, integration.requirements, sanity.requirements
Because setting up a development environment is not exactly straight-forward, we prepared a short instruction manual for new developers.
While the document serves mainly as an installation reference, we also added a few bits of information about the reasons for certain steps that on the first glance only add complexity to the whole thing.
=> Add development environment set up documentation

plugins/doc_fragments/annotations.py, plugins/doc_fragments/auth.py, plugins/doc_fragments/labels.py, plugins/doc_fragments/name.py, plugins/doc_fragments/state.py, plugins/module_utils/arguments.py, plugins/module_utils/base.py, plugins/modules/asset.py, plugins/modules/asset_info.py, plugins/modules/check.py, plugins/modules/check_info.py, plugins/modules/entity.py, plugins/modules/entity_info.py, plugins/modules/filter.py, plugins/modules/filter_info.py, plugins/modules/handler_info.py, plugins/modules/handler_set.py, plugins/modules/hook.py, plugins/modules/hook_info.py, plugins/modules/mutator.py, plugins/modules/mutator_info.py, plugins/modules/namespace.py, plugins/modules/namespace_info.py, plugins/modules/pipe_handler.py, plugins/modules/socket_handler.py, plugins/modules/user.py, plugins/modules/user_info.py, tests/unit/module_utils/test_arguments.py
The primary purpose of this PR is twofold. First, we tried to make modules self-documenting. And secondly, we tried to increase the malleability of the shared parameter specification and documentation.
We tried to achieve this by removing the opaque groups of shared parameters and replace them with a function call that lists what argument specifications we need. We did roughly the same thing with documentation and split it into fragments that document each share parameter separately.
=> Make argument spec composable

roles/install/defaults/main.yml, roles/install/tasks/apt/prepare.yml, roles/install/tasks/yum/prepare.yml
This adds a channel variable to both the `yum` and `apt` repository control. This will let users control which channel is added from this list:
https://packagecloud.io/sensu
The immediate use of this will be to having the `prerelease` channel used prior to those packages being moved to `stable`. 
I also did find that the current files were being added with `.list` on the end twice for `apt` lists, like `sensu_stable.list.list`. I've removed the hard coded one from the `filename` attribute in ` roles/install/tasks/apt/prepare.yml`. While it did work, it seemed unintended. I can move that fix out of this PR if needed.
Please let me know if you'd like any tests done for this work. While I haven't done much with that yet, happy to learn and add them.
Should also be noted that this will …
=> Add repository channel control

plugins/module_utils/arguments.py, plugins/module_utils/role_utils.py, plugins/modules/cluster_role.py, plugins/modules/cluster_role_info.py, tests/integration/modules/molecule/cluster_role/Dockerfile.j2, tests/integration/modules/molecule/cluster_role/molecule.yml, tests/integration/modules/molecule/cluster_role/playbook.yml, tests/unit/module_utils/test_arguments.py, tests/unit/module_utils/test_role_utils.py, tests/unit/modules/test_cluster_role.py, tests/unit/modules/test_cluster_role_info.py
This PR is a follow-up of https://github.com/sensu/sensu-go-ansible/pull/70. We add cluster role and cluster role info support as a new modules. Cluster roles adds support for `Cluster-wide resource types` in addition to namespaced resource types.
=> Update cluster_role and cluster_role_info modules

plugins/module_utils/role_utils.py, plugins/modules/cluster_role.py, plugins/modules/role.py, tests/integration/modules/molecule/role/playbook.yml, tests/unit/modules/test_role.py
This PR includes a couple of fixes and minor updates in the `role` module, to bring it in sync with `cluster_role`:
* it adds a validation check to ensure `rules` parameter is provided and non-empty, same as in `cluster_role`*;
* it makes use of custom comparator provided by `role_utils`, to allow determination of roles' equality when `verbs`, `resources` or `resource_names` are equivalent but ordered differently.
* iz pluralizes resource names in integration tests so that they are aligned with valid Sensu resource types.
*Just thinking, would it make sense to move this validation to `role_utils` at some point?
=> Custom comparator and params validation check for the role module

roles/agent/tasks/main.yml, roles/backend/tasks/main.yml, tests/integration/molecule/role_agent_default/playbook.yml, tests/integration/molecule/role_backend_default/playbook.yml
To address #95, we added the group and user ownership of the `/etc/sensu/backend.yml` and `/etc/sensu/agent.yml` files. We also set it to only be accessible to the `sensu:sensu` user and group.
=> Protected access to backend and agent configuration files

plugins/module_utils/role_utils.py, plugins/modules/cluster_role_binding.py, plugins/modules/cluster_role_binding_info.py, plugins/modules/role_binding.py, tests/integration/molecule/module_cluster_role_binding/playbook.yml, tests/integration/scenario.times, tests/unit/modules/test_cluster_role_binding.py, tests/unit/modules/test_cluster_role_binding_info.py
This commit applies the new module structure to `cluster_role_binding` and `cluster_role_binding_info` modules. Cluster role bindings allow assignment of cluster roles to users and groups.
To avoid duplication of module params validation code (which is exactly the same for both `role_binding` and `cluster_role_binding` modules), I added a slightly modified version of the validator previously in `role_binding.py` and moved it to common `utils/role_utils`, where it can be used by both modules.
=> Update cluster_role_binding and cluster_role_binding_info modules

plugins/modules/role_binding.py, tests/integration/molecule/module_role_binding/playbook.yml, tests/unit/modules/test_role_binding.py
From [Sensu Go Role Bindings reference](https://docs.sensu.io/sensu-go/5.14/reference/rbac/#role-bindings-and-cluster-role-bindings):  
> A role binding assigns **a role or cluster role** to users and groups within a namespace.
ATM the `role_binding` module does not allow applying cluster roles in the context of the current namespace, as the `role` parameter expects a "normal" role that acts on namespaced resources (i.e. not a cluster role). In this PR we update the module so that we can specify `cluster_role` as well. The new parameter is mutually exclusive with `role`.
=> Add support for cluster roles in the role_binding module

tests/integration/base.yml
Because Sensu Go 5.15 contains a bug that crashes our test suite, we temporarily disabled the testing on that version.
Once the 5.15.1 is out, we should start testing this again.
=> Disable testing on latest stable Sensu Go

plugins/modules/asset.py, tests/integration/molecule/module_asset/playbook.yml, tests/integration/scenario.times, tests/unit/modules/test_asset.py
This PR modifies the API of the asset module to allow creation of multiple-build assets.
From now on `url`, `sha512`, `filters` and `headers` are no longer top-level arguments of the module, as all of these must/can be provided for individual builds. We introduce the `builds` argument that holds a list of builds with the same argument specification as the prevous single-build specification of the asset.
While the Sensu Go backend API allows top-level `filters` and `headers` when creating an asset in the latest version (`5.15` at the time of writing), this seems to be for backwards-compatibility with the older versions. In the module, we drop support for these in favor of per-build `headers` and `filters` only.
=> Update asset module API to support multiple-build assets

plugins/filter/backends.py, roles/agent/defaults/main.yml, tests/integration/molecule/role_agent_explicit_backend/molecule.yml, tests/integration/molecule/role_agent_explicit_backend/playbook.yml, tests/integration/scenario.times, tests/unit/filter/test_backends.py
In the initial implementation of the automatic agent <-> backend linking, we assumed that the backends group will always be present in the inventory. Of course, we were completely wrong about that ;)
To address the limitation we just described, we moved the group selection into the filter. And while this might feel a bit wrong at the start, it is not all that bad. The filter is already named backends and highly specialized for a certain task. So nothing tragic happened here.
Note that we could still solve this problem in the default variable file using the attr and default filters, but we decided to go with the customized filter route. This keeps markup minimalistic and all the
logic in the python code where we can unit test it.
Fixes #114
=> Make sure agent role works without backends group

tests/integration/molecule/role_install_default/tests/test_installation.py
When we were determining the latest released version, we used an ugly hack that relied on docs.sensu.io redirect to hold the right version information.
Because Sensu changed the documentation site, our tests started to fail. And we have no one but ourselves to blame for that one.
We removed the ugly tests from the repository and while this reduces the comprehensiveness of the tests, we cannot do better right now since there is no canonical place to look for the latest version.
=> Remove flaky tests that relied on external data

plugins/module_utils/utils.py, plugins/modules/datastore.py, plugins/modules/datastore_info.py, plugins/modules/tessen.py, tests/integration/molecule/module_datastore/molecule.yml, tests/integration/molecule/module_datastore/playbook.yml, tests/integration/scenario.times, tests/unit/module_utils/test_utils.py, tests/unit/modules/test_datastore.py, tests/unit/modules/test_datastore_info.py
Datastore module and its info counterpart know how to deal with external datastores.
The payload that the Sensu storage API accepts is a bit different from the payload that core/v2 API endpoints expect, but we kept the user-facing interface similar to all other modules. This way, playbook authors can use their knowledge about existing modules when dealing with data storage.
Fixes #119
=> Add external datastore modules

plugins/action/bonsai_asset.py, tests/unit/action/test_bonsai_asset.py
nice work on the collection!
I came across this error when using `bonsai_asset` with a non-"default" namespace. This is hopefully the correct fix.
=> add namespace support to bonsai_asset

docs/source/release_notes.rst, galaxy.yml
Update release notes and collection metadata in preparation for upcoming 1.1 release.
~Depends on #130~ ~We will fix #130 in a separate patch release since getting support for Sensu Go 5.16 out is semi-urgent.~ Not sure how I managed to miss the #130 update, but the work there was ready.
=> Prepare collection for 1.1.0 release

plugins/action/bonsai_asset.py, tests/unit/action/test_bonsai_asset.py
When Ansible is running on python 2, it converts all strings into unicode type when loading YAML files. And because our validation function did not account for this, all hell break loose on python 2.
This commit introduces a simple fix for this: instead of checking for a fixed type, we use Ansible-provided python-version-specific wrappers for a string type.
Note that we could also use unicode type directly, but since Ansible developers already maintain a cross-version implementation, we might as well use it.
Fixes #134
=> Fix bonsai_asset parameter validation on python 2

.flake8, Makefile, plugins/action/bonsai_asset.py, plugins/modules/check.py, plugins/modules/namespace.py, plugins/modules/namespace_info.py, roles/backend/tasks/main.yml, roles/install/tasks/apt/install.yml, roles/install/tasks/yum/install.yml, sanity.requirements, tests/unit/modules/test_event.py, tests/unit/modules/test_filter.py, tests/unit/modules/test_tessen.py
Import process on Ansible Galaxy runs some static checks on the code that `ansible-test sanity` does not. Changes in this PR add those check to our `sanity` make target.
=> Tighten static analysis

roles/agent/templates/agent.yml.j2, roles/backend/templates/backend.yml.j2
While it is true that the generated configuration files should not be modified manually, they might still get inspected from time to time. And in those cases, having a nice, readable configuration file can
make a significant difference in usability.
But because we do not want to bundle all our template conditional logic into one continuous block that looks like a core dump, we implemented the cleanup by using Jinja's trim modifiers to code blocks.
This way we can almost have a cake and eat it too: the template is readable from the developer's perspective and the generated configuration is concise and clean.
=> Strip empty lines from Sensu configuration files

tests/integration/Makefile
Because our CI runs only tests that are listed in the file with scenario run times, we need to make sure that when a new test is created, it is also timed and timings committed.
The check for this is really simple: we list all of the scenarios in the molecule directory and compare the output with the contents of the timings file. If there is anything different, we abort the run and fail the test.
=> Make sure we run all integration tests

units.requirements
Unfortunately, ansible-test is not compatible with the latest stable coverage package. As a temporary workaround, we now force the coverage version 4.x.
=> Add upper version limit for coverage package

docs/source/release_notes.rst, galaxy.yml
This PR also includes some changes that should be part of the 1.1.1 release, but I forgot to include them. I did split them into a separate commit in order to keep things as clean as possible.
=> Prepare collection for 1.2.0 release

roles/install/tasks/apt/prepare.yml
Up until now, the installation role assumed that the apt's package cache is at least partially up to date. It turned out that this assumption falls flat on its face in the world of cloud images.
Changes in this commit force a cache refresh before any of the preparation processes are started. It may seem a bit expensive to do this at first, but the performance impact is actually negligible since
the update happens anyway when we add a new repo.
=> Fix apt package installation on fresh instances

plugins/modules/user.py, tests/unit/modules/test_user.py
The user module needs to fetch any preexisting users from the backend before it can properly validate the parameter combination we received. Unfortunately, we forgot to handle any errors that stem from this communication with the backend and left the initial GET request unprotected.
=> Catch errors from all user API queries

docs/source/modules.rst, plugins/doc_fragments/auth.py, plugins/module_utils/arguments.py, plugins/module_utils/client.py, tests/integration/Makefile, tests/integration/molecule/misc_api_authentication/molecule.yml, tests/integration/molecule/misc_api_authentication/playbook.yml, tests/integration/scenario.times, tests/unit/module_utils/test_client.py
Sensu Go supports API key authentication since version 5.15.0 and it is about time we also add it as a valid method of authentication.
In order not to break the backward compatibility, we made the API key optional. If the API key is not present in the parameters, we proceed with the username and password login. If the API key is set, we validate it and in the case of failure report the error back to the user.
Note that if the API key is present nut invalid, we do not try to authenticate using username and password. We wrote the code this way on purpose, since silently ignoring authentication failure with something that the user believes is valid is not an option.
=> Add API key authentication support

plugins/modules/asset_info.py, plugins/modules/check_info.py, plugins/modules/cluster_role_binding_info.py, plugins/modules/cluster_role_info.py, plugins/modules/datastore_info.py, plugins/modules/entity_info.py, plugins/modules/event.py, plugins/modules/event_info.py, plugins/modules/filter_info.py, plugins/modules/handler_info.py, plugins/modules/hook_info.py, plugins/modules/mutator_info.py, plugins/modules/namespace_info.py, plugins/modules/role_binding_info.py, plugins/modules/role_info.py, plugins/modules/silence_info.py, plugins/modules/user_info.py
All our info modules falsely advertised that they always contain an object field while in reality, they only contain it if the API call to the backend did not fail in one way or another.
Fixes #160
=> Update return value specification for info modules

plugins/modules/asset.py, tests/integration/molecule/module_asset/playbook.yml
When asked about the asset information, the Sensu backend returns `builds: null` field since 5.16. This confused our comparator because we always expected the builds parameter to be a list if present.
Fixes #150
=> Properly handle assets in a deprecated format

plugins/modules/event.py
Sensu Go backend processes events in an asynchronous fashion, which makes it almost impossible to retrieve the processed event shortly after it has been sent to the backend.
Currently, after we submit an event, we query the backend for the last event. What we get back is one of the following three options:
1. nothing, if our event is the first event ever and the backend did not manage to process it yet;
2. previous event, if there is at least one preexisting event on the backend and our event has not been processed yet;
3. our actual event, if the backend processed our event fast enough.
In the real world setting, the third scenario almost never happens, which means that our event module is returning bogus results most of the time.
To rectify the situation, we now simply return back the …
=> Fake event module result

plugins/module_utils/client.py, plugins/modules/user.py, tests/integration/molecule/module_user/converge.yml, tests/unit/module_utils/test_client.py, tests/unit/modules/test_user.py
Changes in this PR make sure the user module is idempotent and that module's parameters can be set independently from one another.
Fixes #183
=> Make user idempotent

roles/agent/tasks/main.yml, roles/backend/handlers/main.yml, roles/backend/tasks/configure.yml, roles/backend/tasks/start.yml, roles/install/tasks/main.yml, tests/integration/molecule/role_agent_default/converge.yml, tests/integration/molecule/role_agent_secured/converge.yml
Using tags in roles is almost useless since the only way to control 
what gets executed is by using the --[skip-]tags Ansible parameter. We cannot store this information in a configuration file or playbook itself, which makes it rather useless.
Since all of our roles are idempotent, there is little need to skip certain tasks when executing a play. Adding a few seconds to the play runtime should not matter much in vast majority of cases.
There is also one very ugly side to our tags usage: it allows users to break their runs. For example, package installation will fail if the user instructed Ansible to skip the repository setup step.
We never documented the tags, so this change does not break the public API of the roles.
=> Remove tags from our roles

roles/backend/tasks/start.yml, tests/integration/molecule/role_backend_default/molecule.yml
Previously, we unconditionally reported a changed state when we tried to initialize the backend although the change happens only on the first run.
This commit updates the task output appropriately and adds an idempotency test stage to the role integration tests.
=> Make sure backend role returns are idempotent

plugins/module_utils/client.py, tests/integration/molecule/misc_api_authentication/converge.yml, tests/unit/module_utils/test_client.py
Since Sensu Go does not offer any reliable way of checking the API key's validity, we do not validate it upfront as we do with the username and password. Instead, we catch the potential problems with the credentials in the request handler.
Fixes #191
=> Delay API key verification

plugins/module_utils/utils.py, plugins/modules/check.py, tests/integration/molecule/module_check/converge.yml, tests/unit/module_utils/test_utils.py, tests/unit/modules/test_check.py
The payload for creating a check is large and contains quite a few lists that serve as a set of things. All this makes comparing the payloads a bit tougher than for the rest of the resources.
Another source of problems is the backend's tendency to treat the null and empty lists as equivalent, adding yet another place where equality checks can go wrong.
Changes in this commit try to fix all of the idempotency issues we could think of, but there is a slight possibility that we still missed something. But things should be in much better shape now.
Fixes #198
=> Make sure the check module is idempotent

units.requirements
When testing, we need to use the right version of pytest package becase:
1. pytest >= 5 does not support python 2.7 anymore, and
2. pytest >= 6 has some problems with relative imports in     collections.
=> Cap pytest version in different environments

docker/build.sh, docs/source/hacking/docker-images.rst, tests/integration/base.yml, tests/integration/molecule/misc_api_authentication/molecule.yml, tests/integration/molecule/misc_api_cert/molecule.yml, tests/integration/molecule/role_agent_config/molecule.yml, tests/integration/molecule/role_agent_default/molecule.yml, tests/integration/molecule/role_agent_secured/molecule.yml, tests/integration/molecule/role_backend_config/molecule.yml, tests/integration/molecule/role_backend_default/molecule.yml, tests/integration/molecule/role_backend_secured/molecule.yml, tests/integration/molecule/role_install_custom_build/molecule.yml, tests/integration/molecule/role_install_custom_version/molecule.yml, tests/integration/molecule/role_install_default/molecule.yml
We recently migrated Docker images used in molecule integration tests from [DockerHub](https://hub.docker.com/u/xlabsi) to [Quay](https://quay.io/organization/xlab-steampunk) repositories. 
With this commit we ensure that Docker images are pulled from the new source. We also update the helper script for building Docker images so that images are pushed to the new location.
=> Switch to using Docker images from quay.io repositories

.circleci/config.yml
CircleCI started deprecating outdated stuff that is not supported anymore [1]. Fortunately, the only thing that affected us was the
docker version and that one was relatively easy to fix. But there is a nasty twist: when we specify docker version in our remote_docker step, our test times go up by a factor of 1.5 (20 minute runs take 30 minutes with the latest docker version).
We first tried to mitigate the increased test times by bumping the parallelism of our jobs, but unfortunately, this did not fix the issue
because the docker operations started to time out. And because a flaky test is worse than no test (it is waaaaay to easy to get accustomed to seeing errors in CI/CD console and stop reacting to them), we abandoned that approach.
The approach that did work for us was to get rid of …
=> Transition to machine executor

plugins/modules/entity.py, tests/integration/molecule/module_entity/converge.yml, tests/sanity/ignore-2.10.txt
Sensu Go officially supports two entity classes: agent and proxy. Using any other class can lead to undefined behavior of the backend and should not be used in production.
In order to give Ansible users a heads-up about this issue, we added a deprecation warning into Sensu Go Ansible Collection when an unsupported entity class is passed in as a parameter.
=> Deprecate custom entity classes

Makefile
When we implemented the automatic timing of tests, we forgot to adjust the Makefile for integration tests of released packages. This commit fixes that oversight.
=> Fix integration tests for packages on Ansible Galaxy

docs/source/index.rst, docs/source/versioning_sensu_go_installation.rst
Up until now, collection users were forced to come up with their own best practices of making sure proper version of components is
installed. To make this process a bit easier, we added a guide that demonstrates one safe way of using Ansible collection.
=> Add instructions on Sensu Go version pinning

docs/source/index.rst, docs/source/release_policy.rst
In order to clarify what end-users can expect from the releases and what guarantees we offer when it comes to maintenance and compatibility, we added a release policy page to the docs.
=> Add release policy

plugins/modules/user.py, tests/unit/modules/test_user.py
When we initially implemented the user module, we only partially simulated the backend response. We left the credentials in the
payload, which is not something backend would ever do.
This commit fixes this inconsistency and makes sure our tests catch this.
=> Simulate backend response in check mode in user module

plugins/modules/user.py, tests/integration/molecule/module_user/converge.yml, tests/unit/modules/test_user.py
Sensu Go's API allows us to operate using hashed passwords in certain situations. In order to align with the upstream's capabilities, we added password_hash argument to the user module.
Do note that change detection does not work when using hashed passwords because the backend does not return back enough information for us to determine if anything changed.
Fixes #217
=> Add support for hashed passwords in user module

plugins/module_utils/client.py, plugins/modules/user.py, tests/integration/molecule/module_user/converge.yml, tests/unit/module_utils/test_client.py, tests/unit/modules/test_user.py
When the Sensu Go backend is compiled with default settings, no version number is added to the source. Previously, this bad version number caused the user module to fail because the default version value (devel) is not a valid version number.
Changes in this commit handle such version numbers as something waaaay in the future. This allows us to keep all of our logic intact since we are dealing with a valid version. It just happens to be a very large one ;)
Fixes #212
=> Prepare user module for unversioned backends 

roles/install/defaults/main.yml, roles/install/tasks/dnf/install.yml, roles/install/tasks/yum/install.yml
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>
We have a need to downgrade packages internally. This makes `allow_downgrade` a configurable option (defaults to `no`).
=> Make allow_downgrade configurable for dnf/yum

roles/install/tasks/apt/install.yml, roles/install/tasks/yum/install.yml, tests/integration/molecule/role_install_custom_build/converge.yml, tests/integration/molecule/role_install_downgrade/converge.yml, tests/integration/molecule/role_install_downgrade/molecule.yml
In order to make sure package downgrades work as intended, we added an integration test that performs a downgrade process.
Once we run the test, we discovered that apt and yum are having troubles with the downgrade process. Fixing the yum issue was easy: we just had to replace the `state: latest` with the `state: present` when we had a version number specified.
Fixing the apt issue was a bit more tricky because the apt Ansible module does not have a parameter for allowing downgrades. For the time being, we resolved this by adding a `force: true` to the apt invocation. We should remove this temporary hack as soon as the upstream adds options for downgrading packages.
=> Make sure package downgrades work

roles/install/vars/Windows.yml
Sensu released Sensu Go versions 5.21.5 and 6.2.6, and this commit adds information about those packages and makes them available for installation on Windows.
=> Update available package versions

docs/source/installation.rst, galaxy.yml
Because the `ansible.windows` Ansible Collection is not certified yet, hard dependency on that collection will prevent Automation Hub users from installing the Sensu Go Ansible Collection. We also added some additional instructions on how to manually install the Windows Ansible Collection for those users.
Do note that removing the `ansible.windows` dependency from the metadata has one major drawback: execution environments will not be able to manage Windows agent installations.
Fixes #275
=> Remove hard dependency on ansible.windows

plugins/modules/auth_provider_info.py
Fix for auth provider info module in "seealso" string.
We list other auth provider modules related to this one
as they were missing.
=> Fix in seealso string in auth provider info module

roles/agent/meta/argument_specs.yml, roles/backend/meta/argument_specs.yml, roles/install/meta/argument_specs.yml
Ansible Core 2.11 added the ability to document and validate role variables before running the role. This PR implements this support for our Sensu Go roles.
=> Add argument specifications for roles

roles/install/vars/OracleLinux.yml
Installing Sensu Agent on the Oracle Linux Based server results in following error:
```
Could not find or access 'OracleLinux.yml'
Searched in: .../collections/ansible_collections/sensu/sensu_go/roles/install/vars/OracleLinux.yml
```
Since OracleLinux is basically another RHEL fork, symlinking vars in Install role resolved the issue for me.
=> Add support for OracleLinux

.circleci/config.yml, tests/integration/molecule/role_backend_default/molecule.yml
This test is failing because Sensu Go broke change detection in their 6.4.0 version. We must remove this marker once Sensu Go 6.4.1 is out.
=> Mark the default backend test role as xfail

docker/debian-10.docker
From the upstream dodumentation at
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
In addition, when you clean up the apt cache by removing
/var/lib/apt/lists it reduces the image size, since the apt cache
is not stored in a layer. Since the RUN statement starts with
apt-get update, the package cache is always refreshed prior to
apt-get install.
Patch kindly provided by Amin. Thank you!
=> Reduce Debian 10 test image size

.circleci/config.yml, tests/config.yml, tests/sanity/ignore-2.13.txt
The Ansible development branch was bumped to 2.13, which means we need another ignore file. And while we were at it, we also added a test configuration file that allows us to skip testing on Python 2.6 on ansible-core >= 2.12.
=> Update CI setup for Ansible 2.13

Makefile
All other cases install requirements before running. Used same patteren for docs (docs. requirements allready existed).
=> Install requirements for docs, befor trying to build with them

sanity.requirements
We pinned Ansible Lint a whle ago because we needed some urgent fixes
from the alpha version. Now that those fixes are part of the stable
release, we can remove the pin and start using latest stable version.
=> Unpin ansible-lint

plugins/action/bonsai_asset.py, plugins/modules/bonsai_asset.py, tests/integration/molecule/action_bonsai_asset/converge.yml, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.9.txt, tests/unit/plugins/action/test_bonsai_asset.py, tests/unit/plugins/modules/test_bonsai_asset.py
Up until now, we retrieved asset definitions from Sensu Bonsai on the control node. The reasoning for this decision was that there is a higher probability that the control node has access to the bonsai.sensu.io.
This commit allows users to select where the asset definitions should be downloaded. By default, we still download them on the control node, but for cases where the target node is more capable, we allow users to specify that they want to run the download process on the target node.
How does it work? The bonsai_asset action plugin now checks the on_remote parameter and if the parameter is missing or is set to false, performs exactly the same thing as it did before (directly download the asset definition).
If the on_remote parameter is set to true, the bonsai_asset action plugin …
=> Remote bonsai asset definition download

plugins/module_utils/http.py
Fixes TypeError: the JSON object must be str, not 'bytes'
when running with python 3.5 on Debian 9
=> Improve module_utils/http.py python 3.5 compat

plugins/module_utils/client.py, tests/sanity/ignore-2.14.txt
This pull request adds support for `ansible-core 2.14`.
Currently, the CI/CD process is failing. The CI/CD set for the project runs tests against the main development branch of Ansible, which is at the time of writing at version 2.14 and prior to this pull request has not been taken into account.
Failing sanity tests were handled in a similar way than for `ansible-core 2.13`, i.e., by adding `ignore-2.14.txt` file, describing the checks that should be skipped. In addition to that, import of `distutils.version` module was substituted with `ansible.module_utils.compat.version`, keeping the former as a fallback for older Ansible versions.
=> Support ansible-core 2.14

plugins/module_utils/errors.py, plugins/modules/user.py, tests/unit/plugins/modules/test_user.py
Check for bcrypt library and raise exception only where needed.
**Expected result**
The user is created/updated with the defined (bcrypt-ed) password hash.
=> Adding bcrypt check

roles/install/vars/AlmaLinux.yml
It appears that in Alma Linux 9 the `ansible_distribution` variable has changed to `AlmaLinux`:
```
$ ansible -m setup localhost | grep distribution
[WARNING]: No inventory was parsed, only implicit localhost is available
"ansible_distribution": "Rocky",
"ansible_distribution_file_parsed": true,
"ansible_distribution_file_path": "/etc/redhat-release",
"ansible_distribution_file_variety": "RedHat",
"ansible_distribution_major_version": "9",
"ansible_distribution_release": "Blue Onyx",
"ansible_distribution_version": "9.1",
```
Which results in the following error from the install playbook:
```
TASK [sensu.sensu_go.install : Include distro-specific vars (AlmaLinux)] *******
task path: /usr/share/ansible/collections/ansible_collections/sensu/sensu_go/roles/install/tasks/dnf/prepare.yml:2 …
```
=> Add symlink for AlmaLinux.yml for alma linux 9 support

Makefile, docker/ubuntu-20.04.docker, docker/ubuntu-22.04.docker, integration.requirements, molecule.requirements, molecule.yml, roles/install/tasks/apt/prepare.yml, tests/integration/molecule/role_install_custom_build/molecule.yml, tests/integration/molecule/role_install_custom_version/molecule.yml, tests/integration/molecule/role_install_default_deb/molecule.yml
- Docker file configurations for Ubuntu 20.04 and 22.04
- Install ansible.posix with ansible-galaxy for integration tests
- pip molecule packages version bump 
- Add archive.debian.org repo to Debian 9 source.list
=> Versioning compatibility for integration tests
