sensu/sensu-go-ansible

- plugins/doc_fragments/base.py
- plugins/module_utils/arguments.py
- plugins/module_utils/base.py
- plugins/modules/sensu_go_asset.py
- plugins/modules/sensu_go_asset_info.py
- tests/integration/modules/molecule/sensu_go_asset/playbook.yml
- tests/integration/modules/molecule/sensu_go_check/playbook.yml
- tests/integration/modules/molecule/sensu_go_filter/playbook.yml
- tests/integration/modules/molecule/sensu_go_mutator/playbook.yml
- tests/unit/module_utils/test_arguments.py
- tests/unit/modules/common/sensu_go_object.py
- tests/unit/modules/common/sensu_go_object_info.py
- tests/unit/modules/test_sensu_go_check.py
- tests/unit/modules/test_sensu_go_filter.py
- tests/unit/modules/test_sensu_go_mutator.py
Moved username, password, url and namespace under auth argument  as we talked about. Base doc fragment was changed so all other modules and tests needed some refactoring.
> Move username, password, url and namespace to auth argument

- .circleci/config.yml
- tests/integration/modules/molecule/asset/molecule.yml
Changes in this PR add daily integration tests for master and stable branches. It contains quite a few changes because we had to refactor the CircleCI configuration file to allow for future extensions with different python and Ansible versions.
For detailed description, see individual commit messages.
> Introduce daily test

- plugins/modules/asset.py
- tests/integration/modules/molecule/asset/Dockerfile.j2
- tests/integration/modules/molecule/asset/playbook.yml
- tests/unit/modules/test_asset.py
- tests/unit/modules/test_asset_info.py
Remove assets defaults and add `required_if` parameter, so the `url` and `sha512` are not required when deleting asset.
> Remove asset's defaults and update tests

- CODE_OF_CONDUCT.md
- README.md
Commits in this PR fix some minor issues with the accuracy of README file and update CoC document to be in sync with Sensu's official one.
> Metadata fixes

- plugins/modules/handler_set.py
- tests/integration/modules/molecule/handler_set/Dockerfile.j2
- tests/integration/modules/molecule/handler_set/molecule.yml
- tests/integration/modules/molecule/handler_set/playbook.yml
- tests/unit/modules/test_handler_set.py
Last handler in the line. With this commit we introduce `handler_set`.
Closes: #20
> Add handler set module

- tests/integration/modules/molecule/check/Dockerfile.j2
- tests/integration/modules/molecule/check/molecule.yml
Also make `Dockerfile.j2` a symlink poiting to `../shared/Dockerfile.j2`
> Update check's molecule file to run test against multiple versions of sensugo

- plugins/modules/filter.py
I just saw that I forgot to add an example to filter module.
> Add filter example

- docs/source/index.rst
- docs/source/sandbox.rst
This is a first attempt at documenting the use cases that collection covers. We started with a sandbox scenario because this is what most beginners will likely need when setting up a Sensu Go environment for testing.
> Add initial documentation about role usage

- galaxy.yml
No comment really needed here ;)
> Prepare metadata for 1.0.0 release

- docs/source/release_notes.rst
- galaxy.yml
~Depends on #136~
~Depends on #137~
>  Prepare collection for 1.1.1 release

- docs/source/roles/install.rst
- plugins/filter/package_name.py
- roles/install/defaults/main.yml
- roles/install/tasks/apt/install.yml
- roles/install/tasks/apt/prepare.yml
- roles/install/tasks/yum/install.yml
- tests/integration/molecule/role_install_custom_build/molecule.yml
- tests/integration/molecule/role_install_custom_build/playbook.yml
- tests/integration/scenario.times
- tests/unit/filter/test_package_name.py
Changes in this PR add a new variable that controls the build of the package that gets installed. Details are documented in the commit messages.
Fixes #139
> Add build variable to install role

- docs/source/release_notes.rst
- galaxy.yml
Update resources for upcoming 1.4.0 release.
> Release preparation

- plugins/doc_fragments/name.py
- plugins/modules/check.py
This PR contains a few documentation fixes for check module.
Fixes #189
Fixes #182
> Documentation updates

- docs/examples/quickstart/playbook-5.yaml
- docs/examples/quickstart/playbook-6.yaml
- docs/source/index.rst
- docs/source/quickstart-sensu-go-5.rst
- docs/source/quickstart-sensu-go-6.rst
- docs/source/sensu_go_5_6_migration.rst
Changes in this PR make sure users can easily find the instructions for managing the Sensu Go version that they are using.
Fixes #215
> Documentation updates for Sensu Go 6

- plugins/modules/secret.py
- plugins/modules/secret_info.py
- tests/integration/molecule/module_secret/converge.yml
- tests/integration/scenario.times
- tests/unit/modules/test_secret.py
- tests/unit/modules/test_secret_info.py
Changes in current PR introduce two new modules for managing and listing Sensu Go secrets.
Fixes #220
> Add modules for managing Sensu Go secrets

- plugins/doc_fragments/secrets.py
- plugins/module_utils/arguments.py
- plugins/module_utils/utils.py
- plugins/modules/check.py
- plugins/modules/mutator.py
- plugins/modules/pipe_handler.py
- tests/integration/molecule/module_check/converge.yml
- tests/integration/molecule/module_mutator/converge.yml
- tests/integration/molecule/module_pipe_handler/converge.yml
- tests/unit/module_utils/test_utils.py
- tests/unit/modules/test_check.py
- tests/unit/modules/test_mutator.py
- tests/unit/modules/test_pipe_handler.py
> Add support for secrets to check, mutator, and pipe_handler modules

- CODE_OF_CONDUCT.md
Changes in this PR do two things:
1. Add contact information to CoC.
2. Generalize CoC a bit since the previous version was a bit too focused on conferences and other in-person events.
> Coc updates

- plugins/modules/etcd_replicator.py
- plugins/modules/etcd_replicator_info.py
- tests/integration/molecule/module_etcd_replicator/converge.yml
- tests/unit/modules/test_etcd_replicator.py
- tests/unit/modules/test_etcd_replicator_info.py
This is the first part of the federation support, Seconds part (cluster definition) will follow soon.
> Add module for managing etcd replicators

- plugins/modules/cluster.py
- plugins/modules/cluster_info.py
- plugins/modules/etcd_replicator.py
- plugins/modules/etcd_replicator_info.py
- tests/integration/molecule/module_cluster/converge.yml
- tests/integration/molecule/module_etcd_replicator/converge.yml
- tests/unit/modules/test_cluster.py
- tests/unit/modules/test_cluster_info.py
- tests/unit/modules/test_etcd_replicator.py
- tests/unit/modules/test_etcd_replicator_info.py
This is the second part of federation support in the Sensu Go Ansible collection.
> Add modules for managing clusters

- plugins/modules/auth_provider_info.py
- tests/unit/plugins/modules/test_auth_provider_info.py
Resolves #278 
This module fetches existing authentication providers.
> Add auth provider info module

- plugins/modules/ldap_auth_provider.py
- tests/integration/molecule/module_ldap_auth_provider/converge.yml
- tests/unit/plugins/modules/test_ldap_auth_provider.py
Resolves #279
This module allows managing LDAP
authentication providers.
> Add LDAP authentication provider

- plugins/modules/ad_auth_provider.py
- tests/integration/molecule/module_ad_auth_provider/converge.yml
- tests/unit/plugins/modules/test_ad_auth_provider.py
Resolves #280 
This module allows managing AD
authentication providers.
> Add AD authentication provider

- plugins/modules/oidc_auth_provider.py
- tests/integration/molecule/module_oidc_auth_provider/converge.yml
- tests/integration/molecule/module_oidc_auth_provider/molecule.yml
- tests/unit/plugins/modules/test_oidc_auth_provider.py
Resolves #281 
This module allows managing OIDC
authentication providers.
> Add OIDC authentication provider

- plugins/modules/ad_auth_provider.py
- plugins/modules/auth_provider_info.py
- plugins/modules/ldap_auth_provider.py
- tests/integration/molecule/module_ad_auth_provider/converge.yml
- tests/integration/molecule/module_ldap_auth_provider/converge.yml
- tests/integration/molecule/module_oidc_auth_provider/converge.yml
- tests/unit/plugins/modules/test_auth_provider_info.py
Removes password and client_secret from return objects in auth_provider modules.
> Hide param

- roles/install/vars/Windows.yml
Splitted windows part to seperate PR.
> Updated meta data for windows versions

- docker/sensu-6.4.3.docker
- docker/sensu-6.5.5.docker
- docker/sensu-6.6.2.docker
- tests/integration/base.yml
Splitted - no duplication of versions any more
> Sensu 6.6.2 tests

- changelogs/changelog.yaml
- docs/source/release_notes.rst
- galaxy.yml
Added support for sensu version 6.5 and 6.6.
> Upgraded version to 1.12.1.

- plugins/filter/backends.py
- plugins/filter/backends.yml
- plugins/filter/package_name.py
- plugins/filter/package_name.yml
Filter documentation added for:
> Add filter documentation

- docs/source/release_notes.rst
> Release notes

- docs/source/release_notes.rst
Release notes subtitle line was not long enough ...
:angry:
> sanity fix ansible 2.9, 2.10
